services:
  nginx:
    image: nginx:latest
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - my_network

  db:
    image: mysql:8
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: restaurant_bookings
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 30s
    networks:
      - my_network

  backend:
    build: ./server
    container_name: backend
    image: server:1.1
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db:3306
      - DB_USER=root
      - DB_PASSWORD=123
      - DB_NAME=restaurant_bookings
    stdin_open: true
    tty: true
    depends_on:
      db:
        condition: service_healthy
    networks:
      - my_network

  backend2:
    build: ./server
    container_name: backend2
    image: server:1.1
    ports:
      - "8081:8080"
    environment:
      - DB_HOST=db:3306
      - DB_USER=root
      - DB_PASSWORD=123
      - DB_NAME=restaurant_bookings
    stdin_open: true
    tty: true
    depends_on:
      db:
        condition: service_healthy
    networks:
      - my_network

  frontend:
    build: ./client
    container_name: frontend
    image: go-training-2025-frontend
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - backend
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

volumes:
  db_data:
    driver: local
