PUST ${REST_API_URL}/owners/:owner_id/restaurants/58
Content-Type: application/json
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImdtYWlsIjoiaGlldWxlMjQ1MjAwM0BnbWFpbC5jb20iLCJyb2xlIjoib3duZXIiLCJleHAiOjE3NDMxNjE5MjB9.y7o1AKL3ZDhT4jRpfIRqjbuHUWtv3lumpSbr1AoDrRo