GET http://localhost:8080/staff/restaurant
content-Type: application/json
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsImdtYWlsIjoiaGlldWxlMjQ1MjAwM0BnbWFpbC5jb20iLCJyb2xlIjoic3RhZmYiLCJleHAiOjE3NDUzMTQzNTJ9.YVdgRM8hvBf6u5I1NAWrKhpZJ2N7M9OYR-Uc90NVxec