POST ${process.env.REACT_APP_API_URL}/register
content-Type: application/json 

{
    "Name": "owner",
	"Email": "hieulee1@gmail.com",
	"Password":"Lengochieu@245",
	"Phone": "0921658465",
	"Role":  "owner"
}