# http{

# upstream backend {
#         server backend:8080;
#         server backend2:8080; 
#     }

    server {
    }
        listen 80;
        server_name localhost;
        location / {
        proxy_pass http://frontend:3000;
        proxy_cache_valid 200 1h;
        
    }
    location /api/ {
        proxy_pass http://backend:8080;
        rewrite ^/api/(.*)$ /$1 break;
    }
# }
