server {
    upstream backend {
        server backend:8080;
        server backend2:8080; 
    }


    listen 80;
    server_name localhost;
    location / {
        proxy_pass http://frontend:3000;
        
    }
    location /api/ {
        proxy_pass http://backend;
        rewrite ^/api/(.*)$ /$1 break;
    }
}
