POST http://localhost:8080/change-password
Content-Type: application/json
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImdtYWlsIjoiaGlldWxuMjQ1QGdtYWlsLmNvbSIsInJvbGUiOiJjdXN0b21lciIsImV4cCI6MTc0MjgxMTE5N30.5MbQyK7yLcsH37CjMpX2M9F6u7vAnI4A6EnDlZGjf-U

{
    "OldPassword":"Lengochieu123",
    "NewPassword":"Lengochieu@123"
}