POST http://localhost:8080/restaurants/create
content-Type: application/json
authentication: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImdtYWlsIjoiaGlldWxlZTI0NUBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3NDIyNzYwODV9.o_b3sgklG1jlhO-b9xkDGHPQt0mjg3i9tKXF8mx8XzA

{
    "Name": "Kien Restaurant", 
    "Description": "Nha hang cua su tin tuong",
    "Started" : "8:00",
    "Ended" : "22:00",
    "Owner_id": 1
}