GET http://localhost:8080/owners/:owner_id/restaurants
Content-Type: application/json
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImdtYWlsIjoiYWRtaW5AZ21haWwuY29tIiwicm9sZSI6Im93bmVyIiwiZXhwIjoxNzQyOTc5NjcwfQ.rG5H_lUS2HwYGt5cRpWp8RN9uVRzet3w9VW0dQFD16U