POST http://localhost:8080/owners/2/58/staffs/:staff_id
Content-Type: application/json
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImdtYWlsIjoiaGlldWxlMjQ1MjAwM0BnbWFpbC5jb20iLCJyb2xlIjoib3duZXIiLCJleHAiOjE3NDMwNzcxNTh9.whe65P6IvT_HX2KpMmdcubJqPtp015lShUoTa6v8LdU

{
    "Status": "inactive",
    "Id" : 7
}